-- Initial schema for the event system.
--
-- Row IDs are text and generated by the client (crypto.randomUUID()), so the
-- UI can update optimistically before the server responds. Tables, zones and
-- guests are keyed by (event_id, id) so each event owns its own ID space.
--
-- All access goes through the Next.js API routes using the server-only secret
-- key, which bypasses RLS. RLS is enabled with no policies so the public
-- (publishable/anon) key can't read or write anything directly.

create table public.events (
  id text primary key default gen_random_uuid()::text,
  couple_names text not null,
  event_date date not null,
  venue text not null default '',
  guests_invited integer not null default 0 check (guests_invited >= 0),
  status text not null default 'planning'
    check (status in ('planning', 'confirmed', 'completed')),
  phase text not null default 'SETUP'
    check (phase in ('SETUP', 'RSVP_CAMPAIGN', 'SEATING', 'LOCKED_PRE_EVENT', 'LIVE', 'POST_EVENT')),
  created_at timestamptz not null default now()
);

create table public.seating_tables (
  event_id text not null references public.events (id) on delete cascade,
  id text not null,
  -- Preserves the order rows were added in, even within one bulk insert.
  seq bigint generated always as identity,
  name text not null,
  capacity integer not null check (capacity > 0),
  shape text not null check (shape in ('round', 'square')),
  is_reserved boolean not null default false,
  primary key (event_id, id)
);

create table public.seating_zones (
  event_id text not null references public.events (id) on delete cascade,
  id text not null,
  seq bigint generated always as identity,
  name text not null,
  table_ids text[] not null default '{}',
  primary key (event_id, id)
);

create table public.guests (
  event_id text not null references public.events (id) on delete cascade,
  id text not null,
  seq bigint generated always as identity,
  name text not null,
  phone text not null default '',
  category text not null default '',
  party_size integer not null default 1 check (party_size >= 0),
  -- Only meaningful when rsvp_status is 'confirmed'; null means the whole party.
  confirmed_count integer check (confirmed_count >= 0),
  rsvp_status text not null default 'pending_whatsapp'
    check (rsvp_status in ('pending_whatsapp', 'needs_call', 'confirmed', 'declined')),
  -- A guest sits at a table, in a zone, or neither.
  table_id text,
  zone_id text,
  arrived boolean not null default false,
  -- Null on an arrived guest means the whole party showed up.
  arrived_count integer check (arrived_count >= 0),
  contact_count integer not null default 0 check (contact_count >= 0),
  primary key (event_id, id),
  constraint guests_single_seating check (table_id is null or zone_id is null),
  -- Deleting a table or zone unseats its guests.
  constraint guests_table_fk foreign key (event_id, table_id)
    references public.seating_tables (event_id, id) on delete set null (table_id),
  constraint guests_zone_fk foreign key (event_id, zone_id)
    references public.seating_zones (event_id, id) on delete set null (zone_id)
);

create index guests_event_seq_idx on public.guests (event_id, seq);
create index seating_tables_event_seq_idx on public.seating_tables (event_id, seq);
create index seating_zones_event_seq_idx on public.seating_zones (event_id, seq);

alter table public.events enable row level security;
alter table public.seating_tables enable row level security;
alter table public.seating_zones enable row level security;
alter table public.guests enable row level security;
